[package]
name = "tsugumi"
version = "0.1.0"
edition = "2021"
description = "Simple EPUB builder"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
