[package]
name = "tsugumi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
chrono = "0.4.20"
clap = { version = "3.2.16", features = ["derive"] }
image = { version = "0.24.3", default-features = false, features = ["gif", "jpeg", "png"] }
indexmap = "1.9.1"
mime_guess = "2.0.4"
serde = { version = "1.0.142", features = ["derive"] }
serde_yaml = "0.9.4"
tempfile = "3.3.0"
uuid = { version = "1.1.2", features = ["v4"] }
xml-rs = "0.8.4"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
